apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: as
  name: scale-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: scale-test
  template:
    metadata:
      labels:
        app: scale-test
    spec:
      containers:
      - name: cpu-hog
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
